#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app_dir="$PLUSHU_APPS_DIR/$1"

# remove any lingering old iid
if [[ -e "$app_dir/build.old.iid" ]]; then
  docker rmi "$(<"$app_dir/build.old.iid")" > /dev/null 2>&1 || :
  rm -f "$app_dir/build.old.iid"
fi

if [[ -e "$app_dir/build.iid" ]]; then
  mv -f "$app_dir/build.iid" "$app_dir/build.old.iid"
fi
